name: Auto-merge updates
on: pull_request
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
      - if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' && steps.dependabot-metadata.outputs.package-ecosystem != 'docker' }}
        run: gh pr merge --auto --delete-branch --squash "${PR_URL}"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  auto-merge-updates:
    runs-on: ubuntu-latest
    if: ${{ github.actor_id == '158570872' }}
    steps:
      - run: gh pr merge --auto --delete-branch --squash "${PR_URL}"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
