name: Update dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: 30 1 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'monosans' }}
    strategy:
      matrix:
        include:
          - cmd: curl -LsSf https://astral.sh/uv/install.sh | sh && uv tool run poetry lock --no-interaction
            commit-msg: Update poetry.lock
            branch: update/poetry-lock
          - cmd: curl -LsSf https://astral.sh/uv/install.sh | sh && uv tool run pre-commit autoupdate
            commit-msg: Update .pre-commit-config.yaml
            branch: update/pre-commit-config
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: ${{ matrix.cmd }}
      - id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: ${{ matrix.commit-msg }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: ${{ matrix.branch }}
          delete-branch: true
          title: ${{ matrix.commit-msg }}
          body:
